<?php

/**
 * @file
 * Contains address_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function address_api_help($route_name, RouteMatchInterface $route_match): string {
  switch ($route_name) {
    // Main module help for the address_api module.
    case 'help.page.address_api':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides REST API for address module.') . '</p>';
      return $output;

    default:
      return '';
  }
}

/**
 * Implements hook_install().
 */
function address_api_install(): void {
    $permissions = [
        'restful post address_api_query_subdivisions',
        'restful get address_api_china_simple_subdivision_list'
    ];

    // 添加权限
    user_role_grant_permissions(RoleInterface::ANONYMOUS_ID, $permissions);
    user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, $permissions);
}
